pypi:
  stage: deploy
  only:
    - master
  tags:
    - ci.inria.fr
    - small
  image: python
  variables:
    TWINE_USERNAME: $PYPI_USER
    TWINE_PASSWORD: $PYPI_PASS
  script:
    - pip install -U twine
    - python setup.py sdist bdist_wheel
    - twine upload dist/*

gitlab:
  stage: deploy
  only:
    - master
  tags:
    - ci.inria.fr
    - small
  image: python
  script:
    - pip install -U twine
    - python setup.py sdist bdist_wheel
    - TWINE_USERNAME=gitlab-ci-token TWINE_PASSWORD=${CI_JOB_TOKEN} twine upload --verbose --skip-existing --repository-url https://gitlab.inria.fr/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*

