import argparse
from pathlib import Path
import json

import pandas as pd

import matplotlib.pyplot as plt


def main():
    parser = argparse.ArgumentParser(description="2d case simulation.")
    parser.add_argument(
        "-i",
        "--profile-data",
        type=Path,
        default="./aggregated_profile.json",
        help="Profile data in JSON format generated by torch.profiler.",
    )

    parser.add_argument(
        "-o",
        "--output-dir",
        type=Path,
        default="./",
        help="Output directory where the files will be written.",
    )

    # Get arguments
    args = parser.parse_args()
    fname = args.profile_data
    output_dir = args.output_dir

    # Load profile data
    with open(fname, "r") as f:
        profile_data = json.load(f)

    df = pd.DataFrame(profile_data)
    breakpoint()


if __name__ == "__main__":
    main()
